---
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, fonts.css, animate.css]
    nature:
      ratio: '16:9'
    includes:
      in_header: fa.html
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(tidyverse)
library(infer)
```

class: left, middle, hide-count

### Statistical inference is the process of making claims about a population based on information from a sample. 

???

Statistical inference is the process of making claims about a population based on information from a sample. We've already learnt about one way to do inference. We used the standard error to construct confidence intervals for a sample mean in the last exercise. Now we're going to extend this way of thinking to the common situation in quantitative research, where we are interested in making comparisons between groups. The most common statistical approach used to make comparisons between groups that you'll come across is within a framework known as frequentist statistics that relies on the concept of hypothesis testing.

---
class: left, top, hide-count

## The hypotheses

.left-column[
Two claims:

1) There is no difference in leadership capability of nurses who have and have not completed a masters degree.  This is the **null hypothesis**, written $H_0$. The difference in leadership scores is **zero**.
$$ H_0: mean(masters)-mean(non-masters)=0 $$


2) There is a difference in leadership capability of nurses who have and have not completed a masters degree. This is the **alternative hypothesis**. The difference in mean scores between groups is **not zero**
$$ H_1: mean(masters)-mean(non-masters)≠0$$
]

???

Consider this hypothetical situation. Say we are interested in determining if completing a masters degree has an impact on nurses leadership capabilities. To frame this research question in a way that we can perform statistical inference, we first need to assume that there is no difference in leadership capabilities between the two populations, which are nurses with, and without, a masters degree. In statistical terms, this is termed the null hypothesis. Our statement that there IS a difference in leadership capability between nurses who have completed a masters degree is formally termed the alternative hypothesis. The second step after setting the null and alternative hypotheses, is to use data from a sample drawn from those populations to argue AGAINST the null hypothesis, which, for us, is that there is no difference in leadership capabilities between the two groups of nurses. 

---
class: center, middle, hide-count

### The goal is to *disprove* the null hypothesis. 

???

In simple terms, the goal for hypothesis testing using statistical inference is to DISPROVE the null hypothsis so that you can claim the alternative hypothesis is true. So how are we going to do that. Let's go through the steps in the next video.
