---
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, fonts.css, animate.css]
    nature:
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
      ratio: '16:9'
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(icon)
library(emo)
```

class: center, middle
# Introduction

???

A methodology is a term used to describe how knowledge is discovered and analysed in a systematic way. One thing that is important to remember, is that methodology is distinct from methods. Methodology specifically refers to the philosophies that guide how knowledge should be gathered, whereas methods encompass the actual data gathering techniques. So that would be things like surveys or interviews. 

---

???

One example of a methodology that is aligned with a relativist ontology would be phenomenology. It is common in studies that use phenomenology for the researchers to conduct in-depth interviews with their participants so they can thoroughly understand the context of the situation. This is because it aligns with the epistemology of a researcher who believes that knowledge is derived from experience.

---

class: center, middle

# Up next


???

To sum up what we've learned so far in simple terms, you can use simple logic to match research epistemology and methodology to the appropriate ontology. It's quite common for these assumptions not to be made explicit in a research paper. 


