---
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, fonts.css, animate.css]
    nature:
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
      ratio: '16:9'
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(icon)
library(emo)
```

class: center, middle
# Introduction

???

This week we examine different perspectives on what constitutes knowledge, and how these fundamental assumptions have given rise to various research approaches in nursing.


---

class: left, top

# Objectives

- To understand the nature of the paradigmatic assumptions and the development of theoretical approaches that have guided nursing and health sciences research.

- To situate qualitative and quantitative research approaches within their respective philosophical/epistemological foundations

???

Our objectives are to start to understand the paradigms that have informed the development of different research and theoretical approaches used in nursing and in particular, to situate qualitative and quantitative research within their respective philosophical/epistemological foundations.

---
class: left, middle

# Ontology

# Epistemology

# Methodology

???

First up, I want to introduce you to the terms ontology, epistemology and methodology. Understanding what these terms means will help you understand the basis for different types of quantitative and qualitative research. This is essential because there are implications for appraising and using the evidence derived from the research. Let's look what ontology is first.

---

class: left, middle

# Ontology

><h1>one's beliefs about reality</h1>

???
Basically, ontology is one's beliefs about reality. Different kinds of research are founded on different beliefs about what we think truth is. In other words, what we think reality is, will shape what we think we can know about reality. That is why it is important to understand ontology when you are learning about and critiquing research.

Philosophies about reality can be divided in different ways. When you are just starting to learn about research it helps to understand the two types of ontology that are essentially opposites: 

---

class: left, middle

# Realism

# Relativism

???
These are Realism and Relativism. Once you understand these two types of ontology you can more easily understand others.

First let's look into realism. 

---

class: left, top

# Realism

><h1>one truth exists</h1>


???

In simple terms, realists believe that one truth exists and that truth does not change. If this is what the researcher thinks about reality it will influence every single decision that is made in a study. So if you are a realist, you believe that the truth can be discovered using objective measurements and that once you find out what the truth is you can generalize it to other situations.

---

class: left, top

# Relativism

><h1>multiple versions of reality</h1>

???

The opposite view of reality is called relativism. Relativists believe in multiple versions of reality. For relativists, what is real is going to depend on the meaning you attach to it. And since reality is created by how we see things, it is going to evolve and change depending on your experiences. Because reality for relativists is context bound it cannot be generalized. It can only be transferred to other similar contexts.


---

class: center, middle

# Up next


???

Before we move on to epistemology, let's move on to a quick exercise to see how one's ontology may implicitly inform their choice of research design.



