---
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, fonts.css, animate.css]
    nature:
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
      ratio: '16:9'
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(icon)
library(emo)
```

class:  center, middle

# Introduction

???

First up, I want to introduce you to a pragmatic approach to knolwedge translation, which is outlined in further detail in the textbook. 

---


class:  left, top

# Knowledge Translation Process
> Perry, cited in Craig & Smith (2012)

--


### `r icon::fa("arrow-right")` Identify the problem

--

### `r icon::fa("arrow-right")` Understand the context

--

### `r icon::fa("arrow-right")` Knowledge

--

### `r icon::fa("arrow-right")` Implement intervention

--

### `r icon::fa("arrow-right")` Maintain and sustain change



???



All knowledge translation strategies of course begin with identification of some sort of problem. Unfortunately, many knowledge translation activities are launched in response to an adverse event or some other patient safety concern or a near miss that has occurred at a local institution. It may also be in response to higher level stategic objectives or directives set at national levels.

Understanding contextual information about the institution and the people who's behaviour the change is expected to influence is essential for successful knowledge translation. This could be done using an environmental scan or SWOT analysis. Several tools that have been validated to assess clinicians' 'readiness for change', which can be very useful information to have at hand when figuring out the level of engagement that is going to be required. In this stage we need to consider what are the barriers and facilitators for change. Typically, this would require engaging with key decision-makers in an organisation.

A detailed analysis and appraisal of the quality of evidence to support the change in practice is also required. 

Then, the implementation process is very complex. It is typically best to pilot test implementations or have 'dry runs' and evaluate how well they went prior to full-scale roll out. Involving champions and opinion leaders is a requirement in order to achieve broader engagement.

Throughout the implementation, process data should be collected in order to evaluate how effectively the knowledge translation is proceeding. 

And finally, a knowledge translatation activity should rarely consist of a linear process with an identifiable start and end-point. We need to be prepared to make changes if things don't work as expected and it is often the case that active strategies are required to sustain the changes over time. 


---


class:  center, middle

# Reading

???

The paper in the next section summarizes and organises some of the foundational work that has been undertaken over the last couple of decades in knowledge translation. In particular, it emphasises the importance of matching the theory or framework guiding a knowledge translation initiative to the purpose and focus of the project being undertaken. 