---
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, fonts.css, animate.css]
    ratio: '16:9'
    includes:
      in_header: fa.html
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(tidyverse)
library(infer)
```

class: center, middle, hide-count

## Introduction

???

Up to now I've focused these lessons on statistical inference on the example of mean scores between two groups. Although this is a common situation encountered in quantitative research, there are lots and lots of different statistical tests that can be used. I do want to introduce you to some of them, but first want to highlight that the principles we've already learned about p-values, null hypotheses, confidence intervals etc, they all still apply regardless of the particular type of statistical tests used in a study. So it's not really important for you to know whether or not the researcher chose the right type of statistical test, but it is important that you can appraise the appropriateness of the conclusions that were drawn from those analyses, which in most cases are drawn from the statistical signficance, or in other words the p value, as well as hopefully the uncertainty associated with the result, which is of course the range of the confidence interval. So for example, wherever you see a p-value reported in a paper, a good thing to do is think to yourself, what is the null hypothesis associated with that p-value. ok - lets get to it.

---

class: center, middle, hide-count

## Common statistical tests

???

The choice of a statistical test largely depends on the types of variables that have been measured. Last week we went over the different types of variables. In our previous example where we compared leadership scores between groups, we had one numerical variable, which was the leadership score, and one nominal variable, which was whether or not nurses had a masters or bachelors degree. In these circumstances where a numerical variable is the outcome and the predictor is nominal it will be common to see research studies reporting results of t-tests. When both the outcome and the predictor are categorical, a common type of statistical test is called the chi square test. If a researcher is interested in the association between two numerical variables, it is common to see correlations. 