---
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: [default, fonts.css, animate.css]
    nature:
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
      ratio: '16:9'
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(icon)
library(emo)
```

class:  top, left

### Contribute one primary (original) post and one substantive response to a colleague each week

### Divided into groups for discussion

### Please keep posts succinct (200 words)

### Use APA referencing

### Grading outline in the syllabus

???

Because this course is run online, participating in the discussion boards are going to be a really important, as it is the primary way for you to interact with your peers and the teaching team. For that reason, we have some firm expectations around your participation in the discussion groups and you will also be graded on the quality of your posts. The primary expectation is that each week you contribute one original post and at least one substantive response to one of your peers. This is just the minimum requirement. You are more than welcome to contribute more to the discussion. It's also important to use APA style referencing in your posts, as that is the expectation for the other written assignments in the course as well. Probably a good idea to take  a look at the syllabus for more information on grading.  